AttributeBonus.create!(limit:   1, bonus: -25, label: "joke")
AttributeBonus.create!(limit:   2, bonus: -23, label:   "pathetic")
AttributeBonus.create!(limit:   3, bonus: -21, label:   "pathetic")
AttributeBonus.create!(limit:   4, bonus: -19, label:   "pathetic")
AttributeBonus.create!(limit:   5, bonus: -17, label:   "pathetic")
AttributeBonus.create!(limit:   6, bonus: -15, label:   "pathetic")
AttributeBonus.create!(limit:   7, bonus: -14, label:   "pathetic")
AttributeBonus.create!(limit:   8, bonus: -13, label:   "pathetic")
AttributeBonus.create!(limit:   9, bonus: -12, label:   "pathetic")
AttributeBonus.create!(limit:  10, bonus: -11, label:   "pathetic")
AttributeBonus.create!(limit:  11, bonus: -10, label:  "very poor")
AttributeBonus.create!(limit:  15, bonus:  -9, label:  "very poor")
AttributeBonus.create!(limit:  18, bonus:  -8, label:  "very poor")
AttributeBonus.create!(limit:  21, bonus:  -7, label:  "very poor")
AttributeBonus.create!(limit:  24, bonus:  -6, label:  "very poor")
AttributeBonus.create!(limit:  27, bonus:  -5, label:       "poor")
AttributeBonus.create!(limit:  30, bonus:  -4, label:       "poor")
AttributeBonus.create!(limit:  32, bonus:  -3, label:       "poor")
AttributeBonus.create!(limit:  36, bonus:  -2, label:       "poor")
AttributeBonus.create!(limit:  40, bonus:  -1, label:       "poor")
AttributeBonus.create!(limit:  59, bonus:   0, label:    "average")
AttributeBonus.create!(limit:  63, bonus:   1, label:       "good")
AttributeBonus.create!(limit:  67, bonus:   2, label:       "good")
AttributeBonus.create!(limit:  71, bonus:   3, label:      "great")
AttributeBonus.create!(limit:  74, bonus:   4, label:      "great")
AttributeBonus.create!(limit:  77, bonus:   5, label:      "great")
AttributeBonus.create!(limit:  80, bonus:   6, label:      "great")
AttributeBonus.create!(limit:  83, bonus:   7, label:       "peak")
AttributeBonus.create!(limit:  86, bonus:   8, label:       "peak")
AttributeBonus.create!(limit:  89, bonus:   9, label:       "peak")
AttributeBonus.create!(limit:  90, bonus:  10, label:       "peak")
AttributeBonus.create!(limit:  91, bonus:  11, label: "superhuman")
AttributeBonus.create!(limit:  92, bonus:  12, label: "superhuman")
AttributeBonus.create!(limit:  93, bonus:  13, label: "superhuman")
AttributeBonus.create!(limit:  94, bonus:  14, label: "superhuman")
AttributeBonus.create!(limit:  95, bonus:  15, label: "superhuman")
AttributeBonus.create!(limit:  96, bonus:  17, label: "superhuman")
AttributeBonus.create!(limit:  97, bonus:  19, label: "superhuman")
AttributeBonus.create!(limit:  98, bonus:  21, label: "superhuman")
AttributeBonus.create!(limit:  99, bonus:  23, label: "superhuman")
AttributeBonus.create!(limit: 100, bonus:  25, label:      "godly")
