# Critical.create!(damage_type: :slash, severity: :A, score_limit: 15, extra_hits: 0, blood_loss: 0, attack_stun_type: :no_attack_stun_applied, attack_stun_rounds: 0, attack_stun_penalty: 0, parry_stun_type: :no_parry_stun_applied, parry_stun_rounds: 0, parry_stun_penalty: 0, message: "")

Critical.create!(damage_type: :slash, severity: :A, score_limit: 5, extra_hits: 0, blood_loss: 0, attack_stun_type: :no_attack_stun_applied, attack_stun_rounds: 0, attack_stun_penalty: 0, parry_stun_type: :no_parry_stun_applied, parry_stun_rounds: 0, parry_stun_penalty: 0, message: ". It could have been way worse.")
Critical.create!(damage_type: :slash, severity: :A, score_limit: 10, extra_hits: 1, blood_loss: 0, attack_stun_type: :no_attack_stun_applied, attack_stun_rounds: 0, attack_stun_penalty: 0, parry_stun_type: :no_parry_stun_applied, parry_stun_rounds: 0, parry_stun_penalty: 0, message: " in what starts as a perfect movement, but ends disappointing.")
Critical.create!(damage_type: :slash, severity: :A, score_limit: 15, extra_hits: 1, blood_loss: 0, attack_stun_type: :no_attack_stun_applied, attack_stun_rounds: 0, attack_stun_penalty: 0, parry_stun_type: :no_parry_stun_applied, parry_stun_rounds: 0, parry_stun_penalty: 0, message: ", missing a vital organ by inches.")
Critical.create!(damage_type: :slash, severity: :A, score_limit: 20, extra_hits: 1, blood_loss: 0, attack_stun_type: :no_attack_stun_applied, attack_stun_rounds: 0, attack_stun_penalty: 0, parry_stun_type: :parry_penalty, parry_stun_rounds: 1, parry_stun_penalty: 5, message: ", biting deep. # recoils.")
Critical.create!(damage_type: :slash, severity: :A, score_limit: 35, extra_hits: 2, blood_loss: 0, attack_stun_type: :no_attack_stun_applied, attack_stun_rounds: 0, attack_stun_penalty: 0, parry_stun_type: :parry_penalty, parry_stun_rounds: 1, parry_stun_penalty: 10, message: ", #'s evasion leaving him off-balance.")
Critical.create!(damage_type: :slash, severity: :A, score_limit: 45, extra_hits: 0, blood_loss: 1, attack_stun_type: :no_attack_stun_applied, attack_stun_rounds: 0, attack_stun_penalty: 0, parry_stun_type: :no_parry_stun_applied, parry_stun_rounds: 0, parry_stun_penalty: 0, message: ", a little blood appearing.")
Critical.create!(damage_type: :slash, severity: :A, score_limit: 50, extra_hits: 2, blood_loss: 0, attack_stun_type: :no_attack_stun_applied, attack_stun_rounds: 0, attack_stun_penalty: 0, parry_stun_type: :parry_penalty, parry_stun_rounds: 1, parry_stun_penalty: 30, message: ". # attempts to ward @ off.")
